@QuantumBands.API_HostAddress = http://localhost:5047

GET {{QuantumBands.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{QuantumBands.API_HostAddress}}/Greeting?name=YourName

###


GET {{QuantumBands.API_HostAddress}}/api/Roles
###

POST {{QuantumBands.API_HostAddress}}/api/Roles
Content-Type: application/json
Accept: application/json

{
    "roleName": "Ma"
}
###

GET {{QuantumBands.API_HostAddress}}/Greeting/error
ASPNETCORE_ENVIRONMENT: Production
###

POST {{QuantumBands.API_HostAddress}}/api/v1/auth/resend-verification-email
Content-Type: application/json
Accept: application/json

{
    "email": "ctphu@gmail.com"
}
###

POST {{QuantumBands.API_HostAddress}}/api/v1/auth/verify-email
Content-Type: application/json
Accept: application/json

{
    "email": "ctphu@gmail.com"
}
###
Acc