name: CI/CD Docker Local Deployment

on:
  push:
    branches:
      - master # Hoặc nhánh chính của bạn

jobs:
  build-and-deploy-local:
    name: Build and Deploy to Local Docker
    runs-on: [self-hosted, Windows] # Đảm bảo runner của bạn có các nhãn này

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deployment script
        env:
          # Truyền các secrets từ GitHub vào làm biến môi trường cho step này
          # File batch sẽ có thể truy cập chúng
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_KEY }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          VERSION: latest
        run: |
          call deploy.bat
        shell: cmd # Chỉ định shell là cmd để thực thi file .bat